version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: twig/twig
    versions:
    - 3.2.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: php
    versions:
    - 8.0.1.pre.apache
    - 8.0.2.pre.apache
    - 8.0.3.pre.apache
